service: ml-backend-challenge
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  memorySize: 512
  timeout: 25
  environment:
    NODE_ENV: ${opt:stage, 'dev'}

functions:
  app:
    handler: src/handler.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

package:
  excludeDevDependencies: true
  patterns:
    - '!tests/**'
    - '!node_modules/**/aws-sdk/**'  # AWS SDK ya está en Lambda por defecto
    - 'src/**' 

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  dotenv:
    path: .env
  serverless-offline:
    httpPort: 3000
    reloadHandler: true